### ISSUE TITLE
Posibles ideas para su proyecto

### ISSUE THREAD

**Issue by ainochu** [knullknave/Practica3AccesoADatos#5]
Hola buenas noches, respecto a su aplicación Java me gustaría comentar algunos puntos que me parecen muy interesantes...Debido a su eficiente desarrollo y su creatividad, creo que no vendría nada mal que la aplicación pudiera ser desarrollada para Android. 

Gracias por su atención.

**Comment by knullknave** [comment]
Hi ainochu, thank you for your interest in my project, but i think that i am more keen on creating a new artificial intelligence than implementing it into an android aplication, but i can assure you that i will replace the actual database with another mor powerfull such as sql server
